/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      // All colors reference CSS custom properties so they auto-switch between themes.
      // Values are space-separated RGB integers (e.g. "16 20 26") defined in styles.css.
      colors: {
        "background":                  "rgb(var(--color-background) / <alpha-value>)",
        "surface":                     "rgb(var(--color-surface) / <alpha-value>)",
        "surface-dim":                 "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-bright":              "rgb(var(--color-surface-bright) / <alpha-value>)",
        "surface-variant":             "rgb(var(--color-surface-variant) / <alpha-value>)",
        "surface-tint":                "rgb(var(--color-surface-tint) / <alpha-value>)",
        "surface-container":           "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-low":       "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container-lowest":    "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-container-high":      "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest":   "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "on-background":               "rgb(var(--color-on-background) / <alpha-value>)",
        "on-surface":                  "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant":          "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "outline":                     "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant":             "rgb(var(--color-outline-variant) / <alpha-value>)",
        "inverse-surface":             "rgb(var(--color-inverse-surface) / <alpha-value>)",
        "inverse-on-surface":          "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
        "primary":                     "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container":           "rgb(var(--color-primary-container) / <alpha-value>)",
        "primary-fixed":               "rgb(var(--color-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim":           "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
        "on-primary":                  "rgb(var(--color-on-primary) / <alpha-value>)",
        "on-primary-container":        "rgb(var(--color-on-primary-container) / <alpha-value>)",
        "on-primary-fixed":            "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant":    "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
        "inverse-primary":             "rgb(var(--color-inverse-primary) / <alpha-value>)",
        "secondary":                   "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-container":         "rgb(var(--color-secondary-container) / <alpha-value>)",
        "secondary-fixed":             "rgb(var(--color-secondary-fixed) / <alpha-value>)",
        "secondary-fixed-dim":         "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
        "on-secondary":                "rgb(var(--color-on-secondary) / <alpha-value>)",
        "on-secondary-container":      "rgb(var(--color-on-secondary-container) / <alpha-value>)",
        "on-secondary-fixed":          "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant":  "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
        "tertiary":                    "rgb(var(--color-tertiary) / <alpha-value>)",
        "tertiary-container":          "rgb(var(--color-tertiary-container) / <alpha-value>)",
        "tertiary-fixed":              "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
        "tertiary-fixed-dim":          "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
        "on-tertiary":                 "rgb(var(--color-on-tertiary) / <alpha-value>)",
        "on-tertiary-container":       "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
        "on-tertiary-fixed":           "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant":   "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
        "error":                       "rgb(var(--color-error) / <alpha-value>)",
        "error-container":             "rgb(var(--color-error-container) / <alpha-value>)",
        "on-error":                    "rgb(var(--color-on-error) / <alpha-value>)",
        "on-error-container":          "rgb(var(--color-on-error-container) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      spacing: {
        xs:             "0.25rem",
        sm:             "0.5rem",
        md:             "1rem",
        lg:             "1.5rem",
        xl:             "2.5rem",
        margin:         "2rem",
        gutter:         "1.5rem",
        unit:           "8px",
        "container-max": "1440px",
      },
      fontFamily: {
        inter:       ["Inter", "sans-serif"],
        "body-lg":   ["Inter"],
        "body-md":   ["Inter"],
        "body-sm":   ["Inter"],
        "h1":        ["Inter"],
        "h2":        ["Inter"],
        "h3":        ["Inter"],
        "label-caps":["Inter"],
        mono:        ["monospace"],
      },
      fontSize: {
        "body-lg":   ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":   ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm":   ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "h1":        ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2":        ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3":        ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps":["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        mono:        ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-6px)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(12px)" },
          to:   { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to:   { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(16px)" },
          to:   { opacity: "1", transform: "translateX(0)" },
        },
        shimmer: {
          from: { backgroundPosition: "200% center" },
          to:   { backgroundPosition: "-200% center" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(78,222,163,0.4)" },
          "50%":      { boxShadow: "0 0 0 6px rgba(78,222,163,0)" },
        },
        blink: {
          "0%, 88%, 100%": { transform: "scaleY(1)" },
          "94%":           { transform: "scaleY(0.08)" },
        },
        "antenna-pulse": {
          "0%":   { filter: "drop-shadow(0 0 2px rgba(78,222,163,0.4))" },
          "100%": { filter: "drop-shadow(0 0 10px rgba(111,251,190,0.9))" },
        },
      },
      animation: {
        float:            "float 4s ease-in-out infinite",
        "slide-up":       "slide-up 0.3s ease forwards",
        "fade-in":        "fade-in 0.3s ease forwards",
        "scale-in":       "scale-in 0.25s ease forwards",
        "slide-in-right": "slide-in-right 0.3s ease forwards",
        shimmer:          "shimmer 2.5s linear infinite",
        "pulse-glow":     "pulse-glow 2s ease-in-out infinite",
        blink:            "blink 5s ease-in-out infinite",
        "antenna-pulse":  "antenna-pulse 2s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [],
}