/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed-dim": "#00dce5",
        "tertiary": "#4edea3",
        "on-error": "#690005",
        "secondary": "#e6feff",
        "error": "#ffb4ab",
        "on-primary-container": "#f8f7ff",
        "inverse-surface": "#dfe2eb",
        "outline-variant": "#424656",
        "inverse-primary": "#0054d6",
        "surface-tint": "#b3c5ff",
        "surface-bright": "#353940",
        "tertiary-container": "#008259",
        "surface-container": "#1c2026",
        "primary-fixed": "#dae1ff",
        "on-secondary-container": "#006c71",
        "outline": "#8c90a1",
        "on-primary-fixed": "#001849",
        "surface-container-high": "#262a31",
        "secondary-container": "#00f4fe",
        "inverse-on-surface": "#2d3137",
        "on-primary": "#002b75",
        "surface": "#10141a",
        "surface-container-highest": "#31353c",
        "on-secondary-fixed": "#002021",
        "on-secondary": "#003739",
        "primary-container": "#0066ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0a0e14",
        "on-tertiary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#10141a",
        "secondary-fixed": "#63f7ff",
        "on-secondary-fixed-variant": "#004f53",
        "on-primary-fixed-variant": "#003fa4",
        "surface-container-low": "#181c22",
        "on-surface": "#dfe2eb",
        "tertiary-fixed": "#6ffbbe",
        "background": "#10141a",
        "primary": "#b3c5ff",
        "on-tertiary": "#003824",
        "on-surface-variant": "#c2c6d8",
        "on-background": "#dfe2eb",
        "on-tertiary-container": "#e1ffec",
        "primary-fixed-dim": "#b3c5ff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-variant": "#31353c"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "0.5rem",
        "xl": "2.5rem",
        "margin": "2rem",
        "gutter": "1.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "unit": "8px",
        "container-max": "1440px",
        "xs": "0.25rem"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "h3": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "h2": ["Inter"],
        "label-caps": ["Inter"],
        "mono": ["monospace"],
        "inter": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "h1": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "mono": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}